// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDW_s3O_AXoXvEBBKM21EmINrcDrtmai5U',
    appId: '1:405870838653:web:b341129154882eb516c214',
    messagingSenderId: '405870838653',
    projectId: 'journeybuddy---amov---2324',
    authDomain: 'journeybuddy---amov---2324.firebaseapp.com',
    storageBucket: 'journeybuddy---amov---2324.appspot.com',
    measurementId: 'G-9LE7PFWMP6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDR6h-6JPkJuO3hcNoEjTCUMKLHQz7b9Y',
    appId: '1:405870838653:android:5412ce12c19ac6dc16c214',
    messagingSenderId: '405870838653',
    projectId: 'journeybuddy---amov---2324',
    storageBucket: 'journeybuddy---amov---2324.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCegTAKz8p0hQOx8Q8UqiqAM3cZhsqnLP8',
    appId: '1:405870838653:ios:8b37280703aba0a716c214',
    messagingSenderId: '405870838653',
    projectId: 'journeybuddy---amov---2324',
    storageBucket: 'journeybuddy---amov---2324.appspot.com',
    androidClientId: '405870838653-0slii8itkom58rkpqhp9vvan8av4pd0t.apps.googleusercontent.com',
    iosClientId: '405870838653-n8edhau20toe3e19l83ba4gcvi3ualtc.apps.googleusercontent.com',
    iosBundleId: 'com.example.journeyBuddyFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCegTAKz8p0hQOx8Q8UqiqAM3cZhsqnLP8',
    appId: '1:405870838653:ios:99b6714b97e3377e16c214',
    messagingSenderId: '405870838653',
    projectId: 'journeybuddy---amov---2324',
    storageBucket: 'journeybuddy---amov---2324.appspot.com',
    androidClientId: '405870838653-0slii8itkom58rkpqhp9vvan8av4pd0t.apps.googleusercontent.com',
    iosClientId: '405870838653-skut5pd0uf2t3vbutn7k1cpqgihuhfir.apps.googleusercontent.com',
    iosBundleId: 'com.example.journeyBuddyFlutter.RunnerTests',
  );
}
